name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: '0 0 * * *'

jobs:
  check-copyright:
    name: check copyright
    runs-on: ubuntu-latest
    steps:
      # Checking out the repository which is to be actioned
      - uses: actions/checkout@v2
      # Implementing action on repository
      - uses: VinnyBabuManjaly/copyright-action@v1.0.0
        with:
          CopyrightString: 'Copyright check\nAll rights reserved (c)\n'
          FileType: '.jsp'
          Path: 'cics-java-liberty-hello-web/'
          
      # Creates pull request with all changes in file
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: aj-test-copyright

  build-mvnw:
    name: Build Maven Wrapper

    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [8, 11, 17, 21]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.jdk }}
          distribution: "semeru"
          cache: maven
      - name: Build with Maven
        run: ./mvnw --batch-mode --update-snapshots --file pom.xml -Djava.version=${{ matrix.jdk }} verify          
      

  build-gradlew:
    name: Build Gradle Wrapper

    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [8, 11, 17, 21]
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.jdk }}
        distribution: 'semeru'
    - uses: gradle/actions/setup-gradle@v3
      with: 
        gradle-version: 8.6
    - name: Build with Gradle
      run: ./gradlew clean build -Pjava_version=${{ matrix.jdk }}     
